apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha
  namespace: uds-next-alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpha
  template:
    metadata:
      labels:
        app: alpha
        demo-message: "{{ .Values.MESSAGE }}"
    spec:
      containers:
        - name: pause
          image: registry.k8s.io/pause:3.10
